mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mygithub?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 123456
  redis:
    host: redis.server
    port: 16379
    password: siderP@ssw0rd

rabbitmq:
  host: rabbitmq.server
  port: 5672
  username: user
  password: user


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
temp:
  file:
    path: /RUNTIME/dsp/tempFile/