server:
    port: 8080

spring:
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 15Mb

zuul:
  prefix: /api
  strip-prefix: true
  routes:
    message-service:
      path: /message-service/**
      serviceId: message-service
    message-api:
      path: /message/**
      serviceId: message-service
      strip-prefix: false

    customer-service:
      path: /customer-service:/**
      serviceId: customer-service
    customer-api:
      path: /customer/**
      serviceId: customer-service
      strip-prefix: false
    dynamic-api:
      path: /dynamic/**
      serviceId: customer-service
      strip-prefix: false
    opportunity-api:
      path: /opportunity/**
      serviceId: customer-service
      strip-prefix: false
    house-api:
      path: /house/**
      serviceId: customer-service
      strip-prefix: false
    member-api:
      path: /member/**
      serviceId: customer-service
      strip-prefix: false

    dealer-service:
      path: /dealer-service/**
      serviceId: dealer-service
    employee-api:
      path: /dealer/employee/**
      serviceId: dealer-service
      strip-prefix: false
    organization-api:
      path: /dealer/organization/**
      serviceId: dealer-service
      strip-prefix: false
    position-api:
      path: /dealer/position/**
      serviceId: dealer-service
      strip-prefix: false
    team-api:
      path: /dealer/team/**
      serviceId: dealer-service
      strip-prefix: false
    scheduling-api:
      path: /dealer/scheduling/**
      serviceId: dealer-service
      strip-prefix: false
    connector-api:
      path: /dealer/connector/**
      serviceId: dealer-service
      strip-prefix: false
    designer-api:
      path: /dealer/designer/**
      serviceId: dealer-service
      strip-prefix: false
    userToXPlan-api:
      path: /dealer/userToXPlan/**
      serviceId: dealer-service
      strip-prefix: false
    content-api:
      path: /content/**
      serviceId: dealer-service
      strip-prefix: false
    tag-api:
      path: /tag/**
      serviceId: dealer-service
      strip-prefix: false
    menu-api:
      path: /menu/**
      serviceId: dealer-service
      strip-prefix: false
    auth-api:
      path: /privilege/auth/**
      serviceId: dealer-service
      strip-prefix: false
    role-api:
      path: /privilege/role/**
      serviceId: dealer-service
      strip-prefix: false
    user-api:
      path: /user/**
      serviceId: dealer-service
      strip-prefix: false
    operationLog-api:
      path: /operationLog/**
      serviceId: dealer-service
      strip-prefix: false
    dict-api:
      path: /dict/**
      serviceId: dealer-service
      strip-prefix: false
    sys-api:
      path: /sys/version/**
      serviceId: dealer-service
      strip-prefix: false

    file-service:
      path: /file-service/**
      serviceId: file-service
    file-api:
      path: /file/**
      serviceId: file-service
      strip-prefix: false

    task-service:
      path: /task-service/**
      serviceId: task-service
    task-api:
      path: /task/**
      serviceId: task-service
      strip-prefix: false
    communication-api:
      path: /communication/**
      serviceId: task-service
      strip-prefix: false

    coupon-service:
      path: /coupon-service/**
      serviceId: coupon-service
    activity-api:
      path: /activity/**
      serviceId: coupon-service
      strip-prefix: false
    coupon-api:
      path: /coupon/**
      serviceId: coupon-service
      strip-prefix: false

    order-service:
      path: /order-service/**
      serviceId: order-service
    brandOrder-api:
      path: /order/brand/**
      serviceId: order-service
      strip-prefix: false
    auditOrder-api:
      path: /order/audit/**
      serviceId: order-service
      strip-prefix: false
    subOrder-api:
      path: /order/sub/**
      serviceId: order-service
      strip-prefix: false
    custOrder-api:
      path: /order/cust/**
      serviceId: order-service
      strip-prefix: false
    sampleOrder-api:
      path: /order/sample/**
      serviceId: order-service
      strip-prefix: false
    supplementOrder-api:
      path: /order/supplement/**
      serviceId: order-service
      strip-prefix: false
    budgetOrder-api:
      path: /order/budget/**
      serviceId: order-service
      strip-prefix: false

    product-service:
      path: /product-service/**
      serviceId: product-service
    product-api:
      path: /product/**
      serviceId: product-service
      strip-prefix: false
    productSeries-api:
      path: /product/series/**
      serviceId: product-service
      strip-prefix: false
    productSogalMaterial-api:
      path: /product/material/sogal/**
      serviceId: product-service
      strip-prefix: false
    productSchmidtMaterial-api:
      path: /product/schmidt/sogal/**
      serviceId: product-service
      strip-prefix: false
    productMilanaMaterial-api:
      path: /product/milana/sogal/**
      serviceId: product-service
      strip-prefix: false

    finance-service:
      path: /finance-service/**
      serviceId: finance-service
    payment-api:
      path: /finance/payment/deposit/**
      serviceId: finance-service
      strip-prefix: false
    refund-api:
      path: /finance/payment/withdraw/**
      serviceId: finance-service
      strip-prefix: false
    tradeMethod-api:
      path: /finance/payment/method/**
      serviceId: finance-service
      strip-prefix: false
    invoice-api:
      path: /finance/invoice/**
      serviceId: finance-service
      strip-prefix: false
    fund-api:
      path: /finance/fund/**
      serviceId: finance-service
      strip-prefix: false
    account-api:
      path: /finance/account/**
      serviceId: finance-service
      strip-prefix: false
    transfer-api:
      path: /finance/transfer/**
      serviceId: finance-service
      strip-prefix: false
    change-api:
      path: /finance/change/**
      serviceId: finance-service
      strip-prefix: false

    channel-service:
      path: /channel-service/**
      serviceId: channel-service
    cooperator-api:
      path: /channel/cooperator/**
      serviceId: channel-service
      strip-prefix: false
    fee-api:
      path: /channel/fee/**
      serviceId: channel-service
      strip-prefix: false
    cooperatorLevel-api:
      path: /channel/cooperator/level/**
      serviceId: channel-service
      strip-prefix: false
    integralRecord-api:
      path: /channel/integral/record/**
      serviceId: channel-service
      strip-prefix: false

    plan-service:
      path: /plan-service/**
      serviceId: plan-service
    plan-api:
      path: /plan/**
      serviceId: plan-service
      strip-prefix: false

    workflow-service:
      path: /workflow-service/**
      serviceId: workflow-service
    workflow-api:
      path: /workflow/**
      serviceId: workflow-service
      strip-prefix: false

    attachment-service:
      path: /attachment-service/**
      serviceId: attachment-service
    attachment-api:
      path: /attachment/**
      serviceId: attachment-service
      strip-prefix: false

    delivery-service:
      path: /delivery-service/**
      serviceId: delivery-service
    delivery-api:
      path: /delivery/**
      serviceId: delivery-service
      strip-prefix: false

    after-sales-service:
      path: /after-sales-service/**
      serviceId: after-sales-service
    after-sales-api:
      path: /afterSales/**
      serviceId: after-sales-service
      strip-prefix: false

    install-service:
      path: /install-service/**
      serviceId: install-service
    install-api:
      path: /install/**
      serviceId: install-service
      strip-prefix: false

    xplan-service:
      path: /xplan-service/**
      serviceId: xplan-service
    xplan-api:
      path: /xplan/**
      serviceId: xplan-service
      strip-prefix: false

    report-service:
      path: /report-service/**
      serviceId: report-service
    report-user-api:
      path: /report/user/**
      serviceId: report-service
      strip-prefix: false
    report-role-api:
      path: /report/role/**
      serviceId: report-service
      strip-prefix: false
    report-group-api:
      path: /report/group/**
      serviceId: report-service
      strip-prefix: false
    report-table-api:
      path: /report/table/**
      serviceId: report-service
      strip-prefix: false

logging:
  file: .log/gateway.log