server:
    port: 8080

spring:
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 15Mb

zuul:
  prefix: /api
  strip-prefix: true
  routes:

    file-service:
      path: /file-service/**
      serviceId: file-service
    file-api:
      path: /file/**
      serviceId: file-service
      strip-prefix: false

logging:
  file: .log/gateway.log